query leave_applicable_between_dates(
	$entity_id: Int!
	$emp_location: jsonb
	$from_date: date
	$to_date: date
) {
	leave_app_holidays(
		where: {
			_and: [
				{
					_or: [
						{ location_codes: { _contains: $emp_location } }
						{ location_codes: { _contains: "ALL" } }
					]
				}
				{ entity_id: { _eq: $entity_id } }
				{ date: { _gt: $from_date } }
				{ date: { _lt: $to_date } }
			]
		}
	) {
		entity_id
		date
		description
		optional
		location_codes
	}
	__typename
}