mutation leave_bal_update($bal : Int , $leave_type : String , $emp_id : Int) {
  update_leave_app_employee_leavebal(
    _set: {bal: $bal}, 
    where: {emp_id: {_eq: $emp_id}, leave_type : { _eq : $leave_type}}) {
    affected_rows
    returning {
      bal
      leave_type
    }
  }
}