query leaves_applicable($entity_id: Int!, $emp_location: jsonb) {
  leave_app_holidays(
    where: {
      _and: [
        {
          _or: [
            { location_codes: { _contains: $emp_location } }
            { location_codes: { _contains: "ALL" } }
          ]
        }
        { entity_id: { _eq: $entity_id } }
      ]
    }
  ) {
    entity_id
    date
    description
    optional
    location_codes
  }
}
