mutation leave_bal_update($bal : Int , $leave_type : String , $emp_id : Int) {
  update_leave_app_employee_leavebal(
    _set: {bal: $bal, leave_type: $leave_type}, where: {emp_id: {_eq: $emp_id}}) {
    affected_rows
    returning {
      bal
      leave_type
    }
  }
}