on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: testing hasura installation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run hasura installation
        uses: ./
       
      
      